### ISSUE TITLE
The generation of a dataset unexpectedly includes the README version history

### ISSUE THREAD

**Issue by Ndpnt** [OpenTermsArchive/engine#1029]
<img width="383" alt="Capture d’écran 2023-10-24 à 14 47 14" src="https://github.com/OpenTermsArchive/engine/assets/1098708/607808b3-ccbb-463e-8d92-4ea61fc486d0">

**Comment by MattiSG** [comment]
On top, the README.md is always a pre-written one, and the README folder contains the README.md of the versions repository.

**Comment by MattiSG** [comment]
Fixed by #1075.
