### ISSUE TITLE
Received HTTP code 403 when trying to fetch a site using Cloudflare

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/engine#316]
Trying to add Roblox service and documents with the following declaration

```json
{
  "name": "Roblox",
  "documents": {
    "Privacy Policy": {
      "fetch": "https://en.help.roblox.com/hc/en-us/articles/115004630823-Roblox-Privacy-and-Cookie-Policy-",
      "select": [".article-body"],
      "remove": [".wysiwyg-text-align-right img"]
    },
    "Terms of Service": {
      "fetch": "https://en.help.roblox.com/hc/en-us/articles/115004647846-Roblox-Terms-of-Use",
      "select": [".article"],
      "remove": [".article-relatives", ".article-footer"]
    },
    "Community Guidelines": {
      "fetch": "https://en.help.roblox.com/hc/en-us/articles/203313410-Roblox-Community-Rules",
      "select": [".article"],
      "remove": [".article-footer", ".article-relatives"]
    }
  }
}
```

I get this node error messages

`
 Error: The document cannot be accessed or its content can not be selected: Received HTTP code 403 when trying to fetch 'https://en.help.roblox.com/hc/en-us/articles/115004630823-Roblox-Privacy-and-Cookie-Policy-'
`

`
Error: The document cannot be accessed or its content can not be selected: Received HTTP code 403 when trying to fetch 'https://en.help.roblox.com/hc/en-us/articles/115004647846-Roblox-Terms-of-Use'
`

`
Error: The document cannot be accessed or its content can not be selected: Received HTTP code 403 when trying to fetch 'https://en.help.roblox.com/hc/en-us/articles/203313410-Roblox-Community-Rules'
`

**Comment by clementbiron** [comment]
Same error trying to add Coinbase documents with following declaration 

```json
{
  "name": "Coinbase",
  "documents": {
    "Privacy Policy": {
      "fetch": "https://www.coinbase.com/legal/privacy",
      "select": [".ComposePageLayout__ContentWrapper-sc-109zw5h-2"],
      "remove": [".SidebarNav__NavigationLinksList-sc-1c3jy97-1"]
    },
    "Trackers Policy": {
      "fetch": "https://www.coinbase.com/legal/cookie",
      "select": [".ComposePageLayout__ContentWrapper-sc-109zw5h-2"],
      "remove": [".SidebarNav__NavigationLinksList-sc-1c3jy97-1"]
    },
    "Terms of Service": {
      "fetch": "https://www.coinbase.com/legal/user_agreement/ireland_europe",
      "select": [".ComposePageLayout__ContentWrapper-sc-109zw5h-2"],
      "remove": [".SidebarNav__NavigationLinksList-sc-1c3jy97-1"]
    }
  }
}
```

`Content inacessible: Error: The document cannot be accessed or its content can not be selected: Received HTTP code 403 when trying to fetch 'https://www.coinbase.com/legal/user_agreement/ireland_europe'`

**Comment by martinratinaud** [comment]
And here is the response of cloudflare

```
Hi there,

Thanks for contacting Cloudflare support. My name is Yuri and I will be looking into this ticket for you.

To add a bot to Cloudflare's allowlist, please submit this online application.

For more information, please see: Frequently asked questions about Cloudflare bot products

Please let us know if you have any further questions or issues.

Yuri | Cloudflare Support
Search the Cloudflare Community for advice and insight.
```

Online application: https://docs.google.com/forms/d/e/1FAIpQLSdqYNuULEypMnp4i5pROSc-uP6x65Xub9svD27mb8JChA_-XA/viewform
FAQ: https://support.cloudflare.com/hc/en-us/articles/360035387431-Frequently-asked-questions-about-Cloudflare-bot-products?source=search

@trujilloelsa @clementbiron @MattiSG I believe we should apply, what about you ?

**Comment by clementbiron** [comment]
Yes ✔️

**Comment by martinratinaud** [comment]
Validation approval just submitted

![docs google com_forms_d_e_1FAIpQLSdqYNuULEypMnp4i5pROSc-uP6x65Xub9svD27mb8JChA_-XA_viewform](https://user-images.githubusercontent.com/4191809/133568877-ff6ef242-adf7-41be-b243-6dce2c6e1e46.png)

Waiting for their answer

**Comment by clementbiron** [comment]
Same for 
```
{
  "name": "GO Sport",
  "documents": {
    "Commercial Terms": {
      "fetch": "https://www.go-sport.com/cgv/",
      "select": ["#content"]
    },
    "Privacy Policy": {
      "fetch": "https://www.go-sport.com/charte-protection-donnees-clients/",
      "select": ["#content"]
    }
  }
}

```

**Comment by clementbiron** [comment]
Same for this declaration https://github.com/OpenTermsArchive/declarations-france/commit/a0e6b465a74d2f60d5a48f014d5219801841c576
