### ISSUE TITLE
Support JSON for document fetch

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/engine#745]
I met a rather particular case when trying to make the document declaration of Disney+.

Fetching the following url `https://www.disneyplus.com/fr-fr/legal/conditions-g%C3%A9n%C3%A9rales-d'abonnement` does not load the correct content (i want Terms of Service in french, i get Privacy Policy in english). 

I suppose that the page script works as follows: when clicking on one of the navigation links it loads the content of a json and replaces the content in the html.

From what I have explored, it seems possible to get the right raw data in the json accessible at this address `https://cdn.registerdisney.go.com/jgc/v8/client/DTCI-DISNEYPLUS.GC.WEB-PROD/document/GTOU_DPLUS_SUB_FR.DEFAULT.xx-XX` but this assumes that we can retrieve json documents.

I don't realize the investment to support such a feature, it's probably too big for a single case.

If anyone finds another solution to get the right version of this document I'm interested.

**Comment by MattiSG** [comment]
Thanks for documenting this @clementbiron!

This indeed at the moment looks like an edge case, we'll keep on listing similar cases here so we can track when it's worth investing in this 🙂

**Comment by MattiSG** [comment]
The content in [the document](https://cdn.registerdisney.go.com/jgc/v8/client/DTCI-DISNEYPLUS.GC.WEB-PROD/document/GTOU_DPLUS_SUB_FR.DEFAULT.xx-XX) is available under the `data.text` property path, with newlines encoded as `\r\n`.
