### ISSUE TITLE
Get the latest version of a specific service and a type of document

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/engine#874]
When i run `npm start <service_id>` command for services who begin to have a lot of documents (for exemple: 15 for Instagram [here](https://github.com/OpenTermsArchive/france-elections-declarations/blob/main/declarations/Instagram.json), 15 for Twitter [here](https://github.com/OpenTermsArchive/france-elections-declarations/blob/main/declarations/Twitter.json)) it's took a few moments. 

To reduce this friction and save time, it would be useful to be able to run this command for one type of document only (especially for maintenance). The command might look like this: `npm start <service_id> <document_type>`

What do you think ?

Don't forget to upvote if you need this possibility ;)

**Comment by MattiSG** [comment]
Done in https://github.com/OpenTermsArchive/engine/pull/951
