### ISSUE TITLE
Linting does not catch JSON errors

### ISSUE THREAD

**Issue by Amustache** [OpenTermsArchive/engine#879]
I think it could be interesting that the linter actually catches careless errors, e.g., forgetting to close a string, or forgetting a coma.

![image](https://user-images.githubusercontent.com/5108539/174085884-0d9ae877-f485-40ce-a013-fc0c142570cb.png)

![image](https://user-images.githubusercontent.com/5108539/174085898-2f000486-351a-47ed-8205-235fa5681b9a.png)

**Comment by MattiSG** [comment]
Fixed by https://github.com/OpenTermsArchive/engine/pull/991 🙂
