### ISSUE TITLE
When 2 `<body />` in DOM, snapshot does not wait for selector

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/engine#932]
This one is tricky

On [this document](https://info.tradera.com/?path=%2Fguide%2Fhur-fungerar-sorteringen-basta-traff), DOM is having a body inside a body

When I use `executeClientScripts` with an existing selector in the final page, such as `.content__plate`, fetcher should wait for this selector to be present and then take the screenshot.

This is what happens but in the resulting snapshot, the selector does not exist.

See it live on the [contribution tool](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&executeClientScripts=true&expertMode=true&name=Tradera&selectedCss[]=.content__plate&url=https%3A%2F%2Finfo.tradera.com%2F%3Fpath%3D%2Fguide%2Fhur-fungerar-sorteringen-basta-traff)

**Comment by MattiSG** [comment]
Cannot reproduce.
