### ISSUE TITLE
When certificate is not fully compliant, fetcher fails

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/engine#934]
Exemple with this [PDF document](https://partnerportal.zalando.com/partners/sfc/servlet.shepherd/document/download/0695q0000052elGAAQ) from Zalando.

```
{
  "name": "Zalando",
  "documents": {
    "Commercial Terms": {
      "fetch": "https://partnerportal.zalando.com/partners/sfc/servlet.shepherd/document/download/0695q0000052elGAAQ"
    }
  }
}
```

It works when using
- Safari
- Brave
- Chrome

But when looking at [the certificate](https://www.sslshopper.com/ssl-checker.html#hostname=https://partnerportal.zalando.com/partners/sfc/servlet.shepherd/document/download/0695q0000052elGAAQ), it seems that is is not fully compliant and thus causing an error in fetching.

This error goes away if we use `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` which is not really what we want here.

Difficult to consider this is not an error on our side as users can download in most modern browsers.

@Ndpnt what do you think?

**Comment by MattiSG** [comment]
We can't reproduce the problem, the browser says:

> This content pack is empty, or contains only links and Google Docs, and cannot be downloaded.

The new document from the Zalando website works without a problem 🙂
