### ISSUE TITLE
Download-only file fails with `net::ERR_ABORTED`

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/engine#937]
Sometimes, a PDF file is added and [receives a 403](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&documentType=Commercial%20Terms&expertMode=true&name=Octopia&url=https%3A%2F%2Fseller.octopia.com%2FDocumentCgmad%2F20220101%2F1ab59132-f68f-4cd8-ae3f-1c2d62c21710%3Fext%3D.pdf) when fetching HTML.

```
{
  "name": "Octopia",
  "documents": {
    "Commercial Terms": {
      "fetch": "https://seller.octopia.com/DocumentCgmad/20220101/1ab59132-f68f-4cd8-ae3f-1c2d62c21710?ext=.pdf"
    }
  }
}
```

Next step is usually to try to `executeClientScripts` and when we do, we get a [`net::ERR_ABORTED` error](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&documentType=Commercial%20Terms&executeClientScripts=true&expertMode=true&name=Octopia&url=https%3A%2F%2Fseller.octopia.com%2FDocumentCgmad%2F20220101%2F1ab59132-f68f-4cd8-ae3f-1c2d62c21710%3Fext%3D.pdf)

```
{
  "name": "Octopia",
  "documents": {
    "Commercial Terms": {
      "fetch": "https://seller.octopia.com/DocumentCgmad/20220101/1ab59132-f68f-4cd8-ae3f-1c2d62c21710?ext=.pdf",
      "executeClientScripts": true
    }
  }
}
```

**Comment by MattiSG** [comment]
Cannot reproduce, the provided example works with `"select": "body"`. Perhaps related to #915 and #900.

**Comment by adurivault** [comment]
I get a similar problem with the following declaration : 
```json
{
  "name": "Aviva",
  "terms": {
    "Terms of Service": {
      "fetch": "https://static.aviva.io/content/dam/aviva-corporate/documents/socialpurpose/pdfs/Aviva-ESG-Investment-Baseline-Exclusions-Policy.pdf", 
    }
  }
}
```

I tried `"executeClientScripts": true` and / or `"select": "body"` , but I encounter same errors as stated above.

**Comment by clementbiron** [comment]
Hey Augustin

I tried localy with your `Aviva` declaration and i cannot reproduce an `net::ERR_ABORTED` error.

I got a `403` error and it's most likely a Web Application Firewall for which there is currently no solution.
```
2025-04-28T10:54:26+02:00 warn  Aviva — Terms of Service                                                    The documents cannot be accessed or their contents can not be selected:
 - Fetch failed: Received HTTP code 403 when trying to fetch 'https://static.aviva.io/content/dam/aviva-corporate/documents/socialpurpose/pdfs/Aviva-ESG-Investment-Baseline-Exclusions-Policy.pdf'
```
