### ISSUE TITLE
Removing service does not correctly launch `test:modified`

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/engine#990]
As shown in [the PR](https://github.com/OpenTermsArchive/contrib-declarations/pull/744), when a service is deleted, even if there is an history file, script does not detect the change and thus launch the `test` command on all services instead of only the removed one.

This causes tests to fail if just one other service is in error.

**Comment by MattiSG** [comment]
This has been fixed since https://github.com/OpenTermsArchive/docs/pull/96. See https://github.com/OpenTermsArchive/contrib-declarations/actions/runs/7477969514/job/20351870306 for proof 🙂
