### ISSUE TITLE
Move repos to new organization

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/engine#995]
In order to keep all OpenTermsArchive projects in the same place, decision has been made to move remaining repositories in `ambanum` organization to the `OpenTermsArchive` organization.

Although everything should be working thanks to the redirections done by GitHub, updating the references in all the related projects is important

First here is the proposal for the naming
- `ambanum/OpenTermsArchive` -> `OpenTermsArchive/engine`
- `ambanum/OpenTermsArchive.org` -> `OpenTermsArchive/opentermsarchive.org`

Here are the projects that will be impacted and need modifications

- [X] [contrib-declarations](https://github.com/OpenTermsArchive/contrib-declarations/pull/824)
- [X] [dating-declarations](https://github.com/OpenTermsArchive/dating-declarations/pull/139)
- [X] [france-declarations](https://github.com/OpenTermsArchive/france-declarations/commit/d57461434dfea16c46f89ced93578980c1dc4341)
- [ ] [pga-declarations](https://github.com/OpenTermsArchive/pga-declarations/pull/137)
- [ ] [template-declarations](https://github.com/OpenTermsArchive/template-declarations/pull/25)
- [X] [sandbox-declarations](https://github.com/OpenTermsArchive/sandbox-declarations/commit/d39cf5eae16f42d300268d51eae744a0bb655b88)
- [X] [p2b-compliance-declarations](https://github.com/OpenTermsArchive/p2b-compliance-declarations/commit/e48490ab1aef12359ac0324f9814a6c35e19d8f8)
- [ ] [OpenTermsArchive](https://github.com/ambanum/OpenTermsArchive/pull/997)
- [ ] [OpenTermsArchive.org](https://github.com/ambanum/OpenTermsArchive.org/pull/208)
- [ ] [contribution-tool](https://github.com/OpenTermsArchive/contribution-tool/pull/138)
- [ ] [terms-types](https://github.com/OpenTermsArchive/terms-types/pull/11)
- [ ] [versions-cleaner](https://github.com/OpenTermsArchive/versions-cleaner)
- [X] [dashlord](https://github.com/OpenTermsArchive/dashlord) ARCHIVED
- [X] [docs](https://github.com/OpenTermsArchive/docs/pull/22/commits/21c5f3008d3cc80a284862fe4861f6d59009533f)

**Comment by martinratinaud** [comment]
@MattiSG can you please confirm the naming of repositories.

Thanks

**Comment by MattiSG** [comment]
Sounds good to me, thanks @martinratinaud! 👍

> * dashlord

Do we really need to maintain our fork considering that we're on the [incubateur instance](https://dashlord.incubateur.net) ? If not, let's just archive / delete that fork!

To note: [our page on beta.gouv.fr](https://github.com/betagouv/beta.gouv.fr/blob/master/content/_startups/open-terms-archive.md) does not need to be updated, we already referenced `GitHub.com/OpenTermsArchive` as the main source code entry point.

**Comment by MattiSG** [comment]
Thanks @martinratinaud, that's really cool!
It just seems that https://github.com/OpenTermsArchive/engine/pull/997 blocks in CI.

**Comment by Kissaki** [comment]
The repo weblink on https://github.com/OpenTermsArchive/contrib-declarations still links to the old repo

**Comment by MattiSG** [comment]
> The repo weblink

I assume you mean the link in the “About” section to the right handside 🙂 If that is the case, it has been updated since then.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/222463/225087614-8872e0d3-c6ae-4758-8dd9-91ce40123f9d.png">

**Comment by MattiSG** [comment]
Please let us know if you find other outdated links! 🙏
